close all;
clear;
clc;

load('./data_900/Test/LSF_5_beta_5_kappa_13_chi_3_iterIn_20_iterOut_2.mat', 'LSF_5');
SegmentationResult = LSF_5;

load('./data_900/TMI_TestSetGT.mat', 'TMI_Train_Mask');
CytoGroundTruth = TMI_Train_Mask;

[meanDice70, ...
meanFNR70_object, ...
meanTPR70_pixel, ...
meanFPR70_pixel, ...
stdDice70, ...
stdTPR70_pixel, ...
stdFPR70_pixel, ...
stdFNo_70] ...
    = evaluateCytoSegmentation(CytoGroundTruth, SegmentationResult);